### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by lukemulcahy** [abemedia/esbuild-plugin-react-virtualized#122]
Hi

When will be next release? Specifically looking for this esbuild v0.23.0 dependency update?

![image](https://github.com/user-attachments/assets/5f4a7b8c-48a6-4fc1-a8e1-6ca3759e9975)

Thanks

**Comment by abemedia** [comment]
Hi @lukemulcahy ,

Since esbuild is a peer dependency you should be able to update it now, ignoring the version in the dev dependency.
