### ISSUE TITLE
Not work on windows

### ISSUE THREAD

**Issue by trend-alan-bie** [abemedia/esbuild-plugin-react-virtualized#22]
Only works on Mac， but not work on windows
It works if I change 
`const filter = /react-virtualized\/dist\/es\/WindowScroller\/utils\/onScroll.js$/;`
to
`const filter = /react-virtualized\\dist\\es\\WindowScroller\\utils\\onScroll.js$/;`

**Comment by abemedia** [comment]
Thanks for raising this. It's a fairly simple fix so I'll sort it ASAP.

**Comment by abemedia** [comment]
Hi @trend-alan-bie 

I've just released a fix. Can you test with version 1.0.3 and see if your problem is resolved?

**Comment by trend-alan-bie** [comment]
@abemedia , I got this error:

`[esbuild-plugin-react-virtualized] "onLoad" filter is not a valid Go regular expression: "react-virtualized\\dist\\es\\WindowScroller\\utils\\onScroll.js$"`

Perhaps we could employ this straightforward solution, as it appears to function effectively on both Mac and Windows:

`const filter = /react-virtualized[\/|\\]dist[\/|\\]es[\/|\\]WindowScroller[\/|\\]utils[\/|\\]onScroll.js$/`

**Comment by abemedia** [comment]
I had considered something like that, however the pipes and escaping of forward slash isn't necessary.
This would do:
```js
const filter = /react-virtualized[/\\]dist[/\\]es[/\\]WindowScroller[/\\]utils[/\\]onScroll.js$/
```
Will update.

**Comment by abemedia** [comment]
Have amended. Want to try again?

**Comment by trend-alan-bie** [comment]
It works now, thank you so much
